Load Data set

In [1]:
import pandas as pd

matches = pd.read_csv("matches.csv")

matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

Create SQL Database

In [ ]:
import sqlite3

conn = sqlite3.connect("ipl.db")

matches.to_sql(
    "matches",
    conn,
    if_exists="replace",
    index=False
)

print("Database Created Successfully")

Database Created Successfully

Top Winning Teams SQL Query

In [3]:
query = """
SELECT winner,
COUNT(*) AS Wins
FROM matches
GROUP BY winner
ORDER BY Wins DESC;
"""

result = pd.read_sql(query, conn)

result

                         winner  Wins
0                Mumbai Indians   109
1           Chennai Super Kings   100
2         Kolkata Knight Riders    92
3   Royal Challengers Bangalore    84
4               Kings XI Punjab    82
5              Rajasthan Royals    75
6              Delhi Daredevils    67
7           Sunrisers Hyderabad    58
8               Deccan Chargers    29
9                 Gujarat Lions    13
10                Pune Warriors    12
11       Rising Pune Supergiant    10
12               Delhi Capitals    10
13         Kochi Tuskers Kerala     6
14      Rising Pune Supergiants     5
15                         None     4

Season Wise Matches

In [4]:
query = """
SELECT season,
COUNT(*) AS Matches
FROM matches
GROUP BY season
ORDER BY season;
"""

season_result = pd.read_sql(query, conn)

season_result

    season  Matches
0     2008       58
1     2009       57
2     2010       60
3     2011       73
4     2012       74
5     2013       76
6     2014       60
7     2015       59
8     2016       60
9     2017       59
10    2018       60
11    2019       60

Top venus

In [5]:
query = """
SELECT venue,
COUNT(*) AS Matches
FROM matches
GROUP BY venue
ORDER BY Matches DESC
LIMIT 10;
"""

venue_result = pd.read_sql(query, conn)

venue_result

                                        venue  Matches
0                                Eden Gardens       77
1                            Wankhede Stadium       73
2                       M Chinnaswamy Stadium       73
3                            Feroz Shah Kotla       67
4   Rajiv Gandhi International Stadium, Uppal       56
5             MA Chidambaram Stadium, Chepauk       49
6                      Sawai Mansingh Stadium       47
7  Punjab Cricket Association Stadium, Mohali       35
8     Maharashtra Cricket Association Stadium       21
9                  Subrata Roy Sahara Stadium       17

Toss Winner Analysis

In [6]:
query = """
SELECT toss_winner,
COUNT(*) AS Toss_Wins
FROM matches
GROUP BY toss_winner
ORDER BY Toss_Wins DESC;
"""

toss_result = pd.read_sql(query, conn)

toss_result

                    toss_winner  Toss_Wins
0                Mumbai Indians         98
1         Kolkata Knight Riders         92
2           Chennai Super Kings         89
3   Royal Challengers Bangalore         81
4               Kings XI Punjab         81
5              Rajasthan Royals         80
6              Delhi Daredevils         80
7           Sunrisers Hyderabad         46
8               Deccan Chargers         43
9                 Pune Warriors         20
10                Gujarat Lions         15
11               Delhi Capitals         10
12         Kochi Tuskers Kerala          8
13      Rising Pune Supergiants          7
14       Rising Pune Supergiant          6

Close Connection

In [7]:
conn.close()

 1. Mumbai Indians and Chennai Super Kings are among the most successful IPL teams.

 2. IPL match count increased over multiple seasons.

 3. Some venues host significantly more matches than others.

 4. Toss victory does not always guarantee match victory.

 5. Historical IPL data provides useful insights into team performance and tournament trends.

In [ ]:
# Screenshot 1:

# Top Winning Teams

# Screenshot 2:

# Season Wise Matches

# Screenshot 3:

# Top Venues

# Screenshot 4:

# Toss Winner Analysis